version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "security-fixes"
    labels:
      - "dependencies"
    assignees:
      - "joseph-henry"
