---
kind: pipeline
type: docker
name: docs.zerotier.com

platform:
  arch: amd64
  os: linux

clone:
  depth: 1

steps:
  - name: build
    image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/central-builder
    commands:
      - echo $${DOCKER_PASSWORD} | docker login --username $${DOCKER_LOGIN} --password-stdin registry.zerotier.com
      - make docker
      - docker push $${DOCKER_REGISTRY}/zerotier/docs.zerotier.com:drone-${DRONE_BUILD_NUMBER}
    environment:
      DOCKER_LOGIN:
        from_secret: docker-registry-login
      DOCKER_PASSWORD:
        from_secret: docker-registry-password
      DOCKER_REGISTRY:
        from_secret: docker-registry-host
  - name: deploy-to-docs-dev
    image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/central-builder
    depends_on:
      - build
    commands:
      - echo $${GCP_CREDENTIALS} > /tmp/gcp.json
      - gcloud auth activate-service-account drone-ci@zerotier-central.iam.gserviceaccount.com --key-file /tmp/gcp.json --project $${GCP_PROJECT}
      - gcloud --project $${GCP_PROJECT} container clusters get-credentials $${CLUSTER_NAME} --region $${GCP_REGION}
      - kubectl -n dev set image deployment docs-dev-zerotier-com docs-zerotier-com=$${DOCKER_REGISTRY}/zerotier/docs.zerotier.com:drone-${DRONE_BUILD_NUMBER}
    environment:
      GCP_CREDENTIALS:
        from_secret: gcp-k8s-creds
      USE_GKE_GCLOUD_AUTH_PLUGIN: "True"
      GCP_PROJECT:
        from_secret: gcp-project
      GCP_REGION:
        from_secret: gcp-region
      CLUSTER_NAME:
        from_secret: cluster-name
      GKE_DEPLOYMENT_NAME:
        from_secret: gke-deployment-name
      DOCKER_REGISTRY:
        from_secret: docker-registry-host
    when:
      branch:
        - main
  - name: notify-mattermost-build-failure
    pull: always
    image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/mattermost-notify
    depends_on:
      - build
    environment:
      token:
        from_secret: mattermost-token
      host:
        from_secret: mattermost-host
      channel:
        from_secret: mattermost-channel
      maxRetry: 3
    when:
      status:
        - failure
  - name: notify-mattermost-deploy-failure
    pull: always
    image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/mattermost-notify
    depends_on:
      - deploy-to-docs-dev
    environment:
      token:
        from_secret: mattermost-token
      host:
        from_secret: mattermost-host
      channel:
        from_secret: mattermost-channel
      maxRetry: 3
    when:
      status:
        - failure
trigger:
  event:
    - push
    - pull_request
    - tag
---
kind: pipeline
type: docker
name: deploy-docs
concurrency:
  limit: 1
steps:
  - name: deploy-to-production
    image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/central-builder
    commands:
      - echo $${GCP_CREDENTIALS} > /tmp/gcp.json
      - gcloud auth activate-service-account drone-ci@zerotier-central.iam.gserviceaccount.com --key-file /tmp/gcp.json --project $${GCP_PROJECT}
      - gcloud --project $${GCP_PROJECT} container clusters get-credentials $${CLUSTER_NAME} --region $${GCP_REGION}
      - kubectl set image deployment docs-zerotier-com docs-zerotier-com=$${DOCKER_REGISTRY}/zerotier/docs.zerotier.com:drone-${DRONE_BUILD_PARENT}
    environment:
      GCP_CREDENTIALS:
        from_secret: gcp-k8s-creds
      USE_GKE_GCLOUD_AUTH_PLUGIN: "True"
      GCP_PROJECT:
        from_secret: gcp-project
      GCP_REGION:
        from_secret: gcp-region
      CLUSTER_NAME:
        from_secret: cluster-name
      GKE_DEPLOYMENT_NAME:
        from_secret: gke-deployment-name
      DOCKER_REGISTRY:
        from_secret: docker-registry-host
trigger:
  branch:
    - main
  event:
    - promote
  target:
    - production
---
kind: pipeline
type: docker
name: link-checker
trigger:
  event:
  - cron
  cron:
    - link-checker
steps:
  - name: link-checker
    image: tennox/linkcheck
    commands:
      - linkcheck --external --no-show-redirects https://docs.zerotier.com --skip-file <(echo "example.com\nlocalhost")
---
kind: signature
hmac: 51d3fed16fed56c761eabade1684402c724111c3e5ea02b92751716069832405

...
