/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docsSidebar: [
    // {
    //   type: 'autogenerated',
    //   dirName: '.'
    // },
    "welcome",
    {
      type: "category",
      label: "ZeroTier",
      items: [
        // 'zerotier/ztintro',
        "zerotier/manual",
        "zerotier/rules",
        "zerotier/zerotier.conf",
        "zerotier/multipath",
        "zerotier/moons",
        "zerotier/troubleshooting",
      ],
    },
    {
      "type": "category",
      "label": "my.zerotier.com",
      "items": [
        "central/sso",
      ],
    },
    {
      type: "category",
      label: "SDK",
      items: ["sockets/tutorial.html"],
    },
    {
      type: "category",
      label: "API Docs",
      items: [
        {
          type: "category",
          label: "REST APIs",
          items: [
            {
              type: "category",
              label: "Central",
              items: [
                // {
                //   type: 'link',
                //   label: 'Latest',
                //   href: '/centralv1'
                // },
                {
                  type: "link",
                  label: "V1",
                  href: "/central/v1",
                },
              ],
            },
            {
              type: "category",
              label: "Service",
              items: [
                // {
                //   type: 'link',
                //   label: 'Latest',
                //   href: '/servicev1',
                // },
                {
                  type: "link",
                  label: "V1",
                  href: "/service/v1",
                },
              ],
            },
          ],
        },
        {
          type: "category",
          label: "ZeroTierOne C API",
          items: [
            "autogen/libztcore/files/_zero_tier_one_8h",
            "autogen/libztcore/index_classes",
          ],
        },
        {
          type: "category",
          label: "Sockets C API",
          items: [
            "autogen/libzt/files/_zero_tier_sockets_8h",
            "autogen/libzt/index_classes",
          ],
        },
        {
          type: "link",
          label: "Sockets Java API",
          href: "http://docs.zerotier.com/sockets-java/com/zerotier/sockets/package-summary.html",
        },
      ],
    },
    {
      type: "category",
      label: "Self-Hosting",
      items: ["self-hosting/introduction", "self-hosting/network-controllers", "zeronsd/quickstart"],
    },
    {
      type: "category",
      label: "Devices",
      items: ["devices/synology", "devices/ubiquiti", "devices/qnap", "devices/asustor", "devices/freenas", "devices/western-digital", "devices/mikrotik", "devices/teltonika", "devices/opnsense", "devices/openwrt"],
    },
    {
      type: "category",
      label: "Packages",
      items: ["packages/snap"]
    },
    {
      type: "category",
      label: "Terraform",
        items: [
            "terraform/quickstart",
            "terraform/multicloud-quickstart"
        ],
    }
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};
