/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docsSidebar: [
     {
       type: 'autogenerated',
       dirName: '.'
     },
     {
      type: "category",
      label: "API Docs",
      items: [
        {
          type: "category",
          label: "REST APIs",
          items: [
            {
              type: "category",
              label: "Central",
              items: [
                {
                  type: "link",
                  label: "V1",
                  href: "/central/v1",
                },
              ],
            },
            {
              type: "category",
              label: "Service",
              items: [
                {
                  type: "link",
                  label: "V1",
                  href: "/service/v1",
                },
              ],
            },
          ],
        }
      ]
    }
  ]

};
